#! /bin/sh

/bin/busybox --install -s
clear
echo "SHMAC linux by Håkon Øye Amundsen and Joakim Andersson"

#Mount things needed by this script
mount -t proc proc /proc
mount -t sysfs sysfs /sys

export PATH="/bin:/sbin:/usr/bin:/usr/sbin"

exec /bin/sh

